### ISSUE TITLE
Phase check not working properly

### ISSUE THREAD

**Issue by RasmusFunctions** [Confuser2188/PAC#6]
if you have Op and switch off Phase and then go to a Slab you will always be teleported to the whole block. In addition, in the chat and in the console the AntiCheat message is displayed by phase even though it has turned off and has Op.

And maybe you can insert, which one can adjust from when one is banished?
So what else is stuck in all the blocks that are not a whole block tall.
... And there is something else stuck in flowers and grasses.
And you can not go ladder up

**Comment by Confuser2188** [comment]
Can you test it with latest PAC version (pre3) please ?
