### ISSUE TITLE
Phase Check, InventoryMove Check

### ISSUE THREAD

**Issue by RasmusFunctions** [Confuser2188/PAC#8]
**PAC** version** : 2.0.0-pre5

**Server version** : 1.13

**Plugin list** : PermissionsEx, DKBans, WorldEdit, ChatEx, NametagEdit, OnlyProxyJoin, Tablist, DiscordSRV, OpenInv,WorldGuard

Inventory Move works in gamemode 1.

Phase check:
Phase Check still resets one when you run into a flower or grass. In addition, one is sometimes reset when jumping on a trapdoor or slab.

**Comment by Confuser2188** [comment]
Speed can't detect timer.

MorePackets should detect it. Did you disabled MorePackets check ?

**Comment by RasmusFunctions** [comment]
Oh oke, I put MorePackets at 30 ... Sorry :D
