### ISSUE TITLE
Anti-KillAura doesn't block all KillAura Cheats

### ISSUE THREAD

**Issue by Goonhaven** [Confuser2188/PAC#9]
## General Information

**PAC version** : 2.0.0-pre5

**Server version** : 1.13.1 (own computer, not server this time)

**Plugin list** : PermissionsEx, PlugMan, PAC, WorldEdit, EpicMobs, Vault, Multiverse-Core, Essentials, EssentialsChat, FactionsOne

## Explanation of issue
The Aristois hacked client (https://aristois.net/) can still use KillAura.

## Videos/Screenshots
N/A

**Comment by Confuser2188** [comment]
Current KillAura detection only detects rage modes like hitting entities instantly.
And it's not hard to make bypass for these checks (like this client, hitting after 1 second)

I'll try to make more & better checks for KillAura when most modules are stable.
